<?php
    $lang = array(
        "live" => "I live in",
        "help" => "I can help with",
        "hobby" => "My hobbies",
        "ai" => "Let AI write you an example",
        "subject" => "Your subject here",
        "text" => "Text...",
        "send" => "Send",
        "ai_text" => "Text generated by AI:",
        "lang" => "Language",
    );
?>
